-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity video_gray_live is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    motion_count_out : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of video_gray_live is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "video_gray_live_video_gray_live,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.879700,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=180,HLS_SYN_LUT=1589,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv11_0_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_0_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_355 : STD_LOGIC_VECTOR (10 downto 0) := "01101010101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_5F : STD_LOGIC_VECTOR (7 downto 0) := "01011111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_E0FF : STD_LOGIC_VECTOR (15 downto 0) := "1110000011111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv11_4FF : STD_LOGIC_VECTOR (10 downto 0) := "10011111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv10_2CF : STD_LOGIC_VECTOR (9 downto 0) := "1011001111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_F0 : STD_LOGIC_VECTOR (9 downto 0) := "0011110000";
    constant ap_const_lv11_1AA : STD_LOGIC_VECTOR (10 downto 0) := "00110101010";
    constant ap_const_lv10_1E0 : STD_LOGIC_VECTOR (9 downto 0) := "0111100000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal y : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal motion_count_accum : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal region_mask_accum : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal first_frame : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal x : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal addr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal prev_frame_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal prev_frame_ce1 : STD_LOGIC;
    signal prev_frame_we1 : STD_LOGIC;
    signal prev_frame_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal motion_count_latched : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal region_mask_latched : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal y_loc_1_reg_253 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_12_reg_264 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_user_fu_444_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_bin_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_bin_reg_883 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_888 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_906 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_910 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_y_loc_1_phi_fu_256_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_y_loc_1_reg_253 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_empty_12_phi_fu_267_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_12_reg_264 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_y_loc_3_phi_fu_278_p6 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_y_loc_3_reg_275 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln131_fu_624_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_motion_count_accum_loc_1_reg_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_region_mask_accum_loc_1_reg_299 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_region_idx_1_phi_fu_313_p12 : STD_LOGIC_VECTOR (3 downto 0);
    signal region_idx_fu_680_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_reg_pp0_iter1_region_idx_1_reg_310 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln69_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln70_1_cast_fu_689_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_cast_fu_698_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln99_fu_707_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_motion_count_accum_loc_2_reg_330 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln100_fu_730_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter1_region_mask_accum_loc_2_reg_340 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_motion_count_accum_loc_3_reg_350 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter1_region_mask_accum_loc_3_reg_364 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln66_fu_548_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal first_frame_loc_0_load_load_fu_642_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln134_fu_600_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln105_fu_565_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_addr_load : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_motion_count_latched_load : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_region_mask_latched_load : STD_LOGIC_VECTOR (8 downto 0);
    signal first_frame_loc_0_fu_170 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal region_mask_accum_loc_0_fu_174 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal ap_sig_allocacmp_region_mask_accum_loc_0_load : STD_LOGIC_VECTOR (8 downto 0);
    signal motion_count_accum_loc_0_fu_178 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_sig_allocacmp_motion_count_accum_loc_0_load : STD_LOGIC_VECTOR (15 downto 0);
    signal y_loc_0_fu_182 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal g_fu_499_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_fu_524_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_1_fu_534_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln105_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln108_fu_559_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln62_fu_516_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_data_1_fu_579_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal xor_ln67_1_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln67_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln100_fu_720_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln100_fu_724_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_792_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_151 : BOOLEAN;
    signal ap_condition_631 : BOOLEAN;
    signal ap_condition_635 : BOOLEAN;
    signal ap_condition_641 : BOOLEAN;
    signal ap_condition_645 : BOOLEAN;
    signal ap_condition_188 : BOOLEAN;
    signal ap_condition_652 : BOOLEAN;
    signal ap_condition_657 : BOOLEAN;
    signal ap_condition_249 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component video_gray_live_prev_frame_RAM_2P_LUTRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (0 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component video_gray_live_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    prev_frame_U : component video_gray_live_prev_frame_RAM_2P_LUTRAM_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 57600,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address1 => prev_frame_address1,
        ce1 => prev_frame_ce1,
        we1 => prev_frame_we1,
        d1 => curr_bin_fu_509_p2,
        q1 => prev_frame_q1);

    regslice_both_in_stream_V_data_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component video_gray_live_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    addr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if (((icmp_ln65_1_fu_538_p2 = ap_const_lv1_1) and (icmp_ln65_fu_528_p2 = ap_const_lv1_1))) then 
                    addr <= select_ln105_fu_565_p3;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    addr <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288 <= ap_sig_allocacmp_motion_count_accum_loc_0_load;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288 <= ap_phi_reg_pp0_iter0_motion_count_accum_loc_1_reg_288;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299 <= ap_sig_allocacmp_region_mask_accum_loc_0_load;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299 <= ap_const_lv9_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299 <= ap_phi_reg_pp0_iter0_region_mask_accum_loc_1_reg_299;
                end if;
            end if; 
        end if;
    end process;

    empty_12_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
                    empty_12_reg_264 <= x;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    empty_12_reg_264 <= ap_const_lv11_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_12_reg_264 <= ap_phi_reg_pp0_iter0_empty_12_reg_264;
                end if;
            end if; 
        end if;
    end process;

    first_frame_loc_0_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                first_frame_loc_0_fu_170 <= first_frame;
            elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_reg_910 = ap_const_lv1_1) and (icmp_ln117_reg_906 = ap_const_lv1_1))) then 
                first_frame_loc_0_fu_170 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    motion_count_accum_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (p_user_fu_444_p1 = ap_const_lv1_1))) then 
                    motion_count_accum <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_657)) then 
                    motion_count_accum <= add_ln99_fu_707_p2;
                end if;
            end if; 
        end if;
    end process;

    motion_count_accum_loc_0_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                motion_count_accum_loc_0_fu_178 <= motion_count_accum;
            elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                motion_count_accum_loc_0_fu_178 <= ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6;
            end if; 
        end if;
    end process;

    motion_count_latched_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_249)) then
                if ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_1)) then 
                    motion_count_latched <= ap_const_lv16_0;
                elsif ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_0)) then 
                    motion_count_latched <= ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6;
                end if;
            end if; 
        end if;
    end process;

    region_mask_accum_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (p_user_fu_444_p1 = ap_const_lv1_1))) then 
                    region_mask_accum <= ap_const_lv9_0;
                elsif ((ap_const_boolean_1 = ap_condition_657)) then 
                    region_mask_accum <= or_ln100_fu_730_p2;
                end if;
            end if; 
        end if;
    end process;

    region_mask_accum_loc_0_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                region_mask_accum_loc_0_fu_174 <= region_mask_accum;
            elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                region_mask_accum_loc_0_fu_174 <= ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6;
            end if; 
        end if;
    end process;

    region_mask_latched_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_249)) then
                if ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_1)) then 
                    region_mask_latched <= ap_const_lv9_0;
                elsif ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_0)) then 
                    region_mask_latched <= ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6;
                end if;
            end if; 
        end if;
    end process;

    x_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if ((icmp_ln117_fu_594_p2 = ap_const_lv1_1)) then 
                    x <= ap_const_lv11_0_2;
                elsif ((icmp_ln117_fu_594_p2 = ap_const_lv1_0)) then 
                    x <= add_ln134_fu_600_p2;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    x <= ap_const_lv11_0_1;
                end if;
            end if; 
        end if;
    end process;

    y_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_fu_618_p2 = ap_const_lv1_0) and (icmp_ln117_fu_594_p2 = ap_const_lv1_1))) then 
                y <= add_ln131_fu_624_p2;
            elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_reg_910 = ap_const_lv1_1) and (icmp_ln117_reg_906 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_user_fu_444_p1 = ap_const_lv1_1)))) then 
                y <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    y_loc_0_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                y_loc_0_fu_182 <= y;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                y_loc_0_fu_182 <= ap_phi_mux_y_loc_3_phi_fu_278_p6;
            end if; 
        end if;
    end process;

    y_loc_1_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_151)) then
                if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
                    y_loc_1_reg_253 <= y_loc_0_fu_182;
                elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
                    y_loc_1_reg_253 <= ap_const_lv10_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    y_loc_1_reg_253 <= ap_phi_reg_pp0_iter0_y_loc_1_reg_253;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                curr_bin_reg_883 <= curr_bin_fu_509_p2;
                icmp_ln117_reg_906 <= icmp_ln117_fu_594_p2;
                icmp_ln119_reg_910 <= icmp_ln119_fu_618_p2;
                icmp_ln65_1_reg_892 <= icmp_ln65_1_fu_538_p2;
                icmp_ln65_reg_888 <= icmp_ln65_fu_528_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_reg_910 = ap_const_lv1_1) and (icmp_ln117_reg_906 = ap_const_lv1_1))) then
                first_frame <= ap_const_lv1_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln108_fu_559_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_addr_load) + unsigned(ap_const_lv16_1));
    add_ln131_fu_624_p2 <= std_logic_vector(unsigned(ap_phi_mux_y_loc_1_phi_fu_256_p4) + unsigned(ap_const_lv10_1));
    add_ln134_fu_600_p2 <= std_logic_vector(unsigned(ap_phi_mux_empty_12_phi_fu_267_p4) + unsigned(ap_const_lv11_1));
    add_ln99_fu_707_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288) + unsigned(ap_const_lv16_1));
    and_ln69_fu_656_p2 <= (xor_ln67_fu_645_p2 and xor_ln67_1_fu_651_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((out_stream_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((out_stream_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter1, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((out_stream_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((out_stream_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) or (in_stream_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (out_stream_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_151_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_151 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_188_assign_proc : process(icmp_ln65_reg_888, icmp_ln65_1_reg_892, and_ln69_fu_656_p2)
    begin
                ap_condition_188 <= ((ap_const_lv1_1 = and_ln69_fu_656_p2) and (icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1));
    end process;


    ap_condition_249_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln117_reg_906, icmp_ln119_reg_910)
    begin
                ap_condition_249 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_reg_910 = ap_const_lv1_1) and (icmp_ln117_reg_906 = ap_const_lv1_1));
    end process;


    ap_condition_631_assign_proc : process(icmp_ln73_fu_662_p2, icmp_ln81_fu_674_p2, icmp_ln90_fu_668_p2)
    begin
                ap_condition_631 <= ((icmp_ln90_fu_668_p2 = ap_const_lv1_0) and (icmp_ln81_fu_674_p2 = ap_const_lv1_0) and (icmp_ln73_fu_662_p2 = ap_const_lv1_0));
    end process;


    ap_condition_635_assign_proc : process(icmp_ln73_fu_662_p2, icmp_ln81_fu_674_p2, icmp_ln90_fu_668_p2)
    begin
                ap_condition_635 <= ((icmp_ln90_fu_668_p2 = ap_const_lv1_0) and (icmp_ln81_fu_674_p2 = ap_const_lv1_1) and (icmp_ln73_fu_662_p2 = ap_const_lv1_0));
    end process;


    ap_condition_641_assign_proc : process(icmp_ln73_fu_662_p2, icmp_ln81_fu_674_p2, icmp_ln90_fu_668_p2)
    begin
                ap_condition_641 <= ((icmp_ln90_fu_668_p2 = ap_const_lv1_1) and (icmp_ln81_fu_674_p2 = ap_const_lv1_1) and (icmp_ln73_fu_662_p2 = ap_const_lv1_0));
    end process;


    ap_condition_645_assign_proc : process(icmp_ln73_fu_662_p2, icmp_ln81_fu_674_p2, icmp_ln90_fu_668_p2)
    begin
                ap_condition_645 <= ((icmp_ln90_fu_668_p2 = ap_const_lv1_1) and (icmp_ln81_fu_674_p2 = ap_const_lv1_0) and (icmp_ln73_fu_662_p2 = ap_const_lv1_0));
    end process;


    ap_condition_652_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln117_reg_906, icmp_ln119_reg_910)
    begin
                ap_condition_652 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_reg_910 = ap_const_lv1_1) and (icmp_ln117_reg_906 = ap_const_lv1_1));
    end process;


    ap_condition_657_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln65_reg_888, icmp_ln65_1_reg_892, and_ln69_fu_656_p2)
    begin
                ap_condition_657 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln69_fu_656_p2) and (icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_12_phi_fu_267_p4_assign_proc : process(x, p_user_fu_444_p1, ap_phi_reg_pp0_iter0_empty_12_reg_264)
    begin
        if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
            ap_phi_mux_empty_12_phi_fu_267_p4 <= x;
        elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_empty_12_phi_fu_267_p4 <= ap_const_lv11_0;
        else 
            ap_phi_mux_empty_12_phi_fu_267_p4 <= ap_phi_reg_pp0_iter0_empty_12_reg_264;
        end if; 
    end process;


    ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4_assign_proc : process(icmp_ln65_reg_888, icmp_ln65_1_reg_892, ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288, and_ln69_fu_656_p2, add_ln99_fu_707_p2, ap_phi_reg_pp0_iter1_motion_count_accum_loc_2_reg_330)
    begin
        if (((icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1))) then
            if ((ap_const_lv1_0 = and_ln69_fu_656_p2)) then 
                ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288;
            elsif ((ap_const_lv1_1 = and_ln69_fu_656_p2)) then 
                ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4 <= add_ln99_fu_707_p2;
            else 
                ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_motion_count_accum_loc_2_reg_330;
            end if;
        else 
            ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_motion_count_accum_loc_2_reg_330;
        end if; 
    end process;


    ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6_assign_proc : process(icmp_ln65_reg_888, icmp_ln65_1_reg_892, ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288, ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4, ap_phi_reg_pp0_iter1_motion_count_accum_loc_3_reg_350)
    begin
        if (((icmp_ln65_reg_888 = ap_const_lv1_0) or ((icmp_ln65_1_reg_892 = ap_const_lv1_0) and (icmp_ln65_reg_888 = ap_const_lv1_1)))) then 
            ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6 <= ap_phi_reg_pp0_iter1_motion_count_accum_loc_1_reg_288;
        elsif (((icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1))) then 
            ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6 <= ap_phi_mux_motion_count_accum_loc_2_phi_fu_333_p4;
        else 
            ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6 <= ap_phi_reg_pp0_iter1_motion_count_accum_loc_3_reg_350;
        end if; 
    end process;


    ap_phi_mux_region_idx_1_phi_fu_313_p12_assign_proc : process(region_idx_fu_680_p3, ap_phi_reg_pp0_iter1_region_idx_1_reg_310, icmp_ln73_fu_662_p2, icmp_ln90_fu_668_p2, select_ln70_1_cast_fu_689_p3, select_ln70_cast_fu_698_p3, ap_condition_631, ap_condition_635, ap_condition_641, ap_condition_645, ap_condition_188)
    begin
        if ((ap_const_boolean_1 = ap_condition_188)) then
            if ((ap_const_boolean_1 = ap_condition_645)) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= ap_const_lv4_6;
            elsif ((ap_const_boolean_1 = ap_condition_641)) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= ap_const_lv4_3;
            elsif (((icmp_ln90_fu_668_p2 = ap_const_lv1_1) and (icmp_ln73_fu_662_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= ap_const_lv4_0;
            elsif (((icmp_ln90_fu_668_p2 = ap_const_lv1_0) and (icmp_ln73_fu_662_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= select_ln70_cast_fu_698_p3;
            elsif ((ap_const_boolean_1 = ap_condition_635)) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= select_ln70_1_cast_fu_689_p3;
            elsif ((ap_const_boolean_1 = ap_condition_631)) then 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= region_idx_fu_680_p3;
            else 
                ap_phi_mux_region_idx_1_phi_fu_313_p12 <= ap_phi_reg_pp0_iter1_region_idx_1_reg_310;
            end if;
        else 
            ap_phi_mux_region_idx_1_phi_fu_313_p12 <= ap_phi_reg_pp0_iter1_region_idx_1_reg_310;
        end if; 
    end process;


    ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4_assign_proc : process(icmp_ln65_reg_888, icmp_ln65_1_reg_892, ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299, and_ln69_fu_656_p2, or_ln100_fu_730_p2, ap_phi_reg_pp0_iter1_region_mask_accum_loc_2_reg_340)
    begin
        if (((icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1))) then
            if ((ap_const_lv1_0 = and_ln69_fu_656_p2)) then 
                ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4 <= ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299;
            elsif ((ap_const_lv1_1 = and_ln69_fu_656_p2)) then 
                ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4 <= or_ln100_fu_730_p2;
            else 
                ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4 <= ap_phi_reg_pp0_iter1_region_mask_accum_loc_2_reg_340;
            end if;
        else 
            ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4 <= ap_phi_reg_pp0_iter1_region_mask_accum_loc_2_reg_340;
        end if; 
    end process;


    ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6_assign_proc : process(icmp_ln65_reg_888, icmp_ln65_1_reg_892, ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299, ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4, ap_phi_reg_pp0_iter1_region_mask_accum_loc_3_reg_364)
    begin
        if (((icmp_ln65_reg_888 = ap_const_lv1_0) or ((icmp_ln65_1_reg_892 = ap_const_lv1_0) and (icmp_ln65_reg_888 = ap_const_lv1_1)))) then 
            ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6 <= ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299;
        elsif (((icmp_ln65_1_reg_892 = ap_const_lv1_1) and (icmp_ln65_reg_888 = ap_const_lv1_1))) then 
            ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6 <= ap_phi_mux_region_mask_accum_loc_2_phi_fu_343_p4;
        else 
            ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6 <= ap_phi_reg_pp0_iter1_region_mask_accum_loc_3_reg_364;
        end if; 
    end process;


    ap_phi_mux_y_loc_1_phi_fu_256_p4_assign_proc : process(p_user_fu_444_p1, ap_phi_reg_pp0_iter0_y_loc_1_reg_253, y_loc_0_fu_182)
    begin
        if ((p_user_fu_444_p1 = ap_const_lv1_0)) then 
            ap_phi_mux_y_loc_1_phi_fu_256_p4 <= y_loc_0_fu_182;
        elsif ((p_user_fu_444_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_y_loc_1_phi_fu_256_p4 <= ap_const_lv10_0;
        else 
            ap_phi_mux_y_loc_1_phi_fu_256_p4 <= ap_phi_reg_pp0_iter0_y_loc_1_reg_253;
        end if; 
    end process;


    ap_phi_mux_y_loc_3_phi_fu_278_p6_assign_proc : process(icmp_ln117_fu_594_p2, icmp_ln119_fu_618_p2, ap_phi_mux_y_loc_1_phi_fu_256_p4, ap_phi_reg_pp0_iter0_y_loc_3_reg_275, add_ln131_fu_624_p2)
    begin
        if (((icmp_ln119_fu_618_p2 = ap_const_lv1_0) and (icmp_ln117_fu_594_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_y_loc_3_phi_fu_278_p6 <= add_ln131_fu_624_p2;
        elsif (((icmp_ln119_fu_618_p2 = ap_const_lv1_1) and (icmp_ln117_fu_594_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_y_loc_3_phi_fu_278_p6 <= ap_const_lv10_0;
        elsif ((icmp_ln117_fu_594_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_y_loc_3_phi_fu_278_p6 <= ap_phi_mux_y_loc_1_phi_fu_256_p4;
        else 
            ap_phi_mux_y_loc_3_phi_fu_278_p6 <= ap_phi_reg_pp0_iter0_y_loc_3_reg_275;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_empty_12_reg_264 <= "XXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_motion_count_accum_loc_1_reg_288 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_region_mask_accum_loc_1_reg_299 <= "XXXXXXXXX";
    ap_phi_reg_pp0_iter0_y_loc_1_reg_253 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter0_y_loc_3_reg_275 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter1_motion_count_accum_loc_2_reg_330 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_motion_count_accum_loc_3_reg_350 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_region_idx_1_reg_310 <= "XXXX";
    ap_phi_reg_pp0_iter1_region_mask_accum_loc_2_reg_340 <= "XXXXXXXXX";
    ap_phi_reg_pp0_iter1_region_mask_accum_loc_3_reg_364 <= "XXXXXXXXX";

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_addr_load_assign_proc : process(addr, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, p_user_fu_444_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_user_fu_444_p1 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_addr_load <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_addr_load <= addr;
        end if; 
    end process;


    ap_sig_allocacmp_motion_count_accum_loc_0_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6, motion_count_accum_loc_0_fu_178)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_motion_count_accum_loc_0_load <= ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6;
        else 
            ap_sig_allocacmp_motion_count_accum_loc_0_load <= motion_count_accum_loc_0_fu_178;
        end if; 
    end process;


    ap_sig_allocacmp_motion_count_latched_load_assign_proc : process(motion_count_latched, ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6, first_frame_loc_0_load_load_fu_642_p1, ap_condition_652)
    begin
        if ((ap_const_boolean_1 = ap_condition_652)) then
            if ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_1)) then 
                ap_sig_allocacmp_motion_count_latched_load <= ap_const_lv16_0;
            elsif ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_0)) then 
                ap_sig_allocacmp_motion_count_latched_load <= ap_phi_mux_motion_count_accum_loc_3_phi_fu_353_p6;
            else 
                ap_sig_allocacmp_motion_count_latched_load <= motion_count_latched;
            end if;
        else 
            ap_sig_allocacmp_motion_count_latched_load <= motion_count_latched;
        end if; 
    end process;


    ap_sig_allocacmp_region_mask_accum_loc_0_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6, region_mask_accum_loc_0_fu_174)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_region_mask_accum_loc_0_load <= ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6;
        else 
            ap_sig_allocacmp_region_mask_accum_loc_0_load <= region_mask_accum_loc_0_fu_174;
        end if; 
    end process;


    ap_sig_allocacmp_region_mask_latched_load_assign_proc : process(region_mask_latched, ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6, first_frame_loc_0_load_load_fu_642_p1, ap_condition_652)
    begin
        if ((ap_const_boolean_1 = ap_condition_652)) then
            if ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_1)) then 
                ap_sig_allocacmp_region_mask_latched_load <= ap_const_lv9_0;
            elsif ((first_frame_loc_0_load_load_fu_642_p1 = ap_const_lv1_0)) then 
                ap_sig_allocacmp_region_mask_latched_load <= ap_phi_mux_region_mask_accum_loc_3_phi_fu_367_p6;
            else 
                ap_sig_allocacmp_region_mask_latched_load <= region_mask_latched;
            end if;
        else 
            ap_sig_allocacmp_region_mask_latched_load <= region_mask_latched;
        end if; 
    end process;

    curr_bin_fu_509_p2 <= "1" when (unsigned(g_fu_499_p4) > unsigned(ap_const_lv8_5F)) else "0";
    first_frame_loc_0_load_load_fu_642_p1 <= first_frame_loc_0_fu_170;
    g_fu_499_p4 <= in_stream_TDATA_int_regslice(15 downto 8);
    grp_fu_378_p2 <= "1" when (unsigned(empty_12_reg_264) < unsigned(ap_const_lv11_355)) else "0";
    icmp_ln105_fu_553_p2 <= "1" when (ap_sig_allocacmp_addr_load = ap_const_lv16_E0FF) else "0";
    icmp_ln117_fu_594_p2 <= "1" when (ap_phi_mux_empty_12_phi_fu_267_p4 = ap_const_lv11_4FF) else "0";
    icmp_ln119_fu_618_p2 <= "1" when (ap_phi_mux_y_loc_1_phi_fu_256_p4 = ap_const_lv10_2CF) else "0";
    icmp_ln65_1_fu_538_p2 <= "1" when (trunc_ln65_1_fu_534_p1 = ap_const_lv2_0) else "0";
    icmp_ln65_fu_528_p2 <= "1" when (trunc_ln65_fu_524_p1 = ap_const_lv2_0) else "0";
    icmp_ln73_fu_662_p2 <= "1" when (unsigned(y_loc_1_reg_253) < unsigned(ap_const_lv10_F0)) else "0";
    icmp_ln81_fu_674_p2 <= "1" when (unsigned(y_loc_1_reg_253) < unsigned(ap_const_lv10_1E0)) else "0";
    icmp_ln90_fu_668_p2 <= "1" when (unsigned(empty_12_reg_264) < unsigned(ap_const_lv11_1AA)) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    motion_count_out <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_792_p3),32));
    or_ln100_fu_730_p2 <= (shl_ln100_fu_724_p2 or ap_phi_reg_pp0_iter1_region_mask_accum_loc_1_reg_299);

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(signed(p_data_1_fu_579_p4),24));

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_data_1_fu_579_p4 <= ((curr_bin_fu_509_p2 & select_ln62_fu_516_p3) & select_ln62_fu_516_p3);
    p_user_fu_444_p1 <= in_stream_TUSER_int_regslice;
    prev_frame_address1 <= zext_ln66_fu_548_p1(16 - 1 downto 0);

    prev_frame_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln65_fu_528_p2, icmp_ln65_1_fu_538_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln65_1_fu_538_p2 = ap_const_lv1_1) and (icmp_ln65_fu_528_p2 = ap_const_lv1_1))) then 
            prev_frame_ce1 <= ap_const_logic_1;
        else 
            prev_frame_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    prev_frame_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln65_fu_528_p2, icmp_ln65_1_fu_538_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln65_1_fu_538_p2 = ap_const_lv1_1) and (icmp_ln65_fu_528_p2 = ap_const_lv1_1))) then 
            prev_frame_we1 <= ap_const_logic_1;
        else 
            prev_frame_we1 <= ap_const_logic_0;
        end if; 
    end process;

    region_idx_fu_680_p3 <= 
        ap_const_lv4_7 when (grp_fu_378_p2(0) = '1') else 
        ap_const_lv4_8;
    select_ln105_fu_565_p3 <= 
        ap_const_lv16_0 when (icmp_ln105_fu_553_p2(0) = '1') else 
        add_ln108_fu_559_p2;
    select_ln62_fu_516_p3 <= 
        ap_const_lv8_FF when (curr_bin_fu_509_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln70_1_cast_fu_689_p3 <= 
        ap_const_lv4_4 when (grp_fu_378_p2(0) = '1') else 
        ap_const_lv4_5;
    select_ln70_cast_fu_698_p3 <= 
        ap_const_lv4_1 when (grp_fu_378_p2(0) = '1') else 
        ap_const_lv4_2;
    shl_ln100_fu_724_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv9_1),to_integer(unsigned('0' & zext_ln100_fu_720_p1(9-1 downto 0)))));
    tmp_2_fu_792_p3 <= (ap_sig_allocacmp_region_mask_latched_load & ap_sig_allocacmp_motion_count_latched_load);
    trunc_ln65_1_fu_534_p1 <= ap_phi_mux_y_loc_1_phi_fu_256_p4(2 - 1 downto 0);
    trunc_ln65_fu_524_p1 <= ap_phi_mux_empty_12_phi_fu_267_p4(2 - 1 downto 0);
    xor_ln67_1_fu_651_p2 <= (prev_frame_q1 xor curr_bin_reg_883);
    xor_ln67_fu_645_p2 <= (first_frame_loc_0_fu_170 xor ap_const_lv1_1);
    zext_ln100_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_region_idx_1_phi_fu_313_p12),9));
    zext_ln66_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_addr_load),64));
end behav;
