// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gbt24_gbt24_Pipeline_Row_Loop_Col_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_video_TVALID,
        m_axis_video_TREADY,
        mul_ln9,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        s_axis_video_TDATA,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        mode,
        threshold
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_video_TVALID;
input   m_axis_video_TREADY;
input  [63:0] mul_ln9;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [23:0] s_axis_video_TDATA;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [31:0] mode;
input  [31:0] threshold;

reg ap_idle;
reg m_axis_video_TVALID;
reg s_axis_video_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln32_fu_187_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    s_axis_video_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] mode_read_reg_374;
reg   [0:0] icmp_ln32_reg_383;
reg   [0:0] icmp_ln32_reg_383_pp0_iter2_reg;
reg   [0:0] icmp_ln32_reg_383_pp0_iter3_reg;
reg   [0:0] icmp_ln32_reg_383_pp0_iter4_reg;
reg   [2:0] out_pix_keep_reg_392;
reg   [2:0] out_pix_keep_reg_392_pp0_iter2_reg;
reg   [2:0] out_pix_keep_reg_392_pp0_iter3_reg;
reg   [2:0] out_pix_keep_reg_392_pp0_iter4_reg;
reg   [2:0] out_pix_strb_reg_397;
reg   [2:0] out_pix_strb_reg_397_pp0_iter2_reg;
reg   [2:0] out_pix_strb_reg_397_pp0_iter3_reg;
reg   [2:0] out_pix_strb_reg_397_pp0_iter4_reg;
reg   [0:0] out_pix_user_reg_402;
reg   [0:0] out_pix_user_reg_402_pp0_iter2_reg;
reg   [0:0] out_pix_user_reg_402_pp0_iter3_reg;
reg   [0:0] out_pix_user_reg_402_pp0_iter4_reg;
reg   [0:0] out_pix_last_reg_407;
reg   [0:0] out_pix_last_reg_407_pp0_iter2_reg;
reg   [0:0] out_pix_last_reg_407_pp0_iter3_reg;
reg   [0:0] out_pix_last_reg_407_pp0_iter4_reg;
reg   [0:0] out_pix_id_reg_412;
reg   [0:0] out_pix_id_reg_412_pp0_iter2_reg;
reg   [0:0] out_pix_id_reg_412_pp0_iter3_reg;
reg   [0:0] out_pix_id_reg_412_pp0_iter4_reg;
reg   [0:0] out_pix_dest_reg_417;
reg   [0:0] out_pix_dest_reg_417_pp0_iter2_reg;
reg   [0:0] out_pix_dest_reg_417_pp0_iter3_reg;
reg   [0:0] out_pix_dest_reg_417_pp0_iter4_reg;
reg   [7:0] g_reg_422;
reg   [7:0] g_reg_422_pp0_iter2_reg;
wire   [7:0] b_fu_246_p1;
reg   [7:0] b_reg_427;
wire   [15:0] mul_ln6_1_fu_265_p2;
wire   [15:0] grp_fu_345_p3;
reg   [23:0] ap_phi_mux_out_pix_data_2_phi_fu_170_p6;
wire   [23:0] rgb_out_fu_280_p4;
reg   [23:0] ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167;
wire  signed [23:0] sext_ln61_fu_340_p1;
reg    ap_predicate_pred205_state6;
wire   [23:0] ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167;
reg   [23:0] ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167;
reg   [23:0] ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167;
reg   [23:0] ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167;
reg   [23:0] ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167;
reg   [63:0] indvar_flatten_fu_102;
wire   [63:0] add_ln32_fu_192_p2;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] r_fu_226_p4;
wire   [7:0] mul_ln6_1_fu_265_p0;
wire   [8:0] mul_ln6_1_fu_265_p1;
wire   [15:0] grp_fu_353_p3;
wire   [7:0] gray_fu_271_p4;
wire   [31:0] zext_ln59_fu_291_p1;
wire   [0:0] icmp_ln59_fu_295_p2;
wire   [0:0] outv_fu_300_p2;
wire   [0:0] select_ln60_fu_314_p3;
wire   [7:0] select_ln60_1_fu_322_p3;
wire   [7:0] select_ln59_fu_306_p3;
wire   [16:0] rgb_out_2_fu_330_p4;
wire   [7:0] grp_fu_345_p0;
wire   [6:0] grp_fu_345_p1;
wire   [7:0] grp_fu_353_p0;
wire   [4:0] grp_fu_353_p1;
reg    grp_fu_345_ce;
reg    grp_fu_353_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_345_p00;
wire   [12:0] grp_fu_353_p00;
wire   [15:0] mul_ln6_1_fu_265_p00;
reg    ap_condition_216;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 indvar_flatten_fu_102 = 64'd0;
#0 ap_done_reg = 1'b0;
end

gbt24_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U1(
    .din0(mul_ln6_1_fu_265_p0),
    .din1(mul_ln6_1_fu_265_p1),
    .dout(mul_ln6_1_fu_265_p2)
);

gbt24_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_345_p0),
    .din1(grp_fu_345_p1),
    .din2(mul_ln6_1_fu_265_p2),
    .ce(grp_fu_345_ce),
    .dout(grp_fu_345_p3)
);

gbt24_mac_muladd_8ns_5ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_5ns_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_353_p0),
    .din1(grp_fu_353_p1),
    .din2(grp_fu_345_p3),
    .ce(grp_fu_353_ce),
    .dout(grp_fu_353_p3)
);

gbt24_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_216)) begin
        if (((icmp_ln32_fu_187_p2 == 1'd0) & (mode_read_reg_374 == 32'd0))) begin
            ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167 <= s_axis_video_TDATA;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_102 <= 64'd0;
        end else if (((icmp_ln32_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_102 <= add_ln32_fu_192_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        b_reg_427 <= b_fu_246_p1;
        g_reg_422 <= {{s_axis_video_TDATA[15:8]}};
        icmp_ln32_reg_383 <= icmp_ln32_fu_187_p2;
        out_pix_dest_reg_417 <= s_axis_video_TDEST;
        out_pix_id_reg_412 <= s_axis_video_TID;
        out_pix_keep_reg_392 <= s_axis_video_TKEEP;
        out_pix_last_reg_407 <= s_axis_video_TLAST;
        out_pix_strb_reg_397 <= s_axis_video_TSTRB;
        out_pix_user_reg_402 <= s_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_predicate_pred205_state6 <= (~(mode_read_reg_374 == 32'd0) & ~(mode_read_reg_374 == 32'd1) & (icmp_ln32_reg_383_pp0_iter3_reg == 1'd0));
        g_reg_422_pp0_iter2_reg <= g_reg_422;
        icmp_ln32_reg_383_pp0_iter2_reg <= icmp_ln32_reg_383;
        icmp_ln32_reg_383_pp0_iter3_reg <= icmp_ln32_reg_383_pp0_iter2_reg;
        icmp_ln32_reg_383_pp0_iter4_reg <= icmp_ln32_reg_383_pp0_iter3_reg;
        out_pix_dest_reg_417_pp0_iter2_reg <= out_pix_dest_reg_417;
        out_pix_dest_reg_417_pp0_iter3_reg <= out_pix_dest_reg_417_pp0_iter2_reg;
        out_pix_dest_reg_417_pp0_iter4_reg <= out_pix_dest_reg_417_pp0_iter3_reg;
        out_pix_id_reg_412_pp0_iter2_reg <= out_pix_id_reg_412;
        out_pix_id_reg_412_pp0_iter3_reg <= out_pix_id_reg_412_pp0_iter2_reg;
        out_pix_id_reg_412_pp0_iter4_reg <= out_pix_id_reg_412_pp0_iter3_reg;
        out_pix_keep_reg_392_pp0_iter2_reg <= out_pix_keep_reg_392;
        out_pix_keep_reg_392_pp0_iter3_reg <= out_pix_keep_reg_392_pp0_iter2_reg;
        out_pix_keep_reg_392_pp0_iter4_reg <= out_pix_keep_reg_392_pp0_iter3_reg;
        out_pix_last_reg_407_pp0_iter2_reg <= out_pix_last_reg_407;
        out_pix_last_reg_407_pp0_iter3_reg <= out_pix_last_reg_407_pp0_iter2_reg;
        out_pix_last_reg_407_pp0_iter4_reg <= out_pix_last_reg_407_pp0_iter3_reg;
        out_pix_strb_reg_397_pp0_iter2_reg <= out_pix_strb_reg_397;
        out_pix_strb_reg_397_pp0_iter3_reg <= out_pix_strb_reg_397_pp0_iter2_reg;
        out_pix_strb_reg_397_pp0_iter4_reg <= out_pix_strb_reg_397_pp0_iter3_reg;
        out_pix_user_reg_402_pp0_iter2_reg <= out_pix_user_reg_402;
        out_pix_user_reg_402_pp0_iter3_reg <= out_pix_user_reg_402_pp0_iter2_reg;
        out_pix_user_reg_402_pp0_iter4_reg <= out_pix_user_reg_402_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln32_fu_187_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln32_reg_383_pp0_iter4_reg == 1'd0)) begin
        if ((~(mode_read_reg_374 == 32'd0) & ~(mode_read_reg_374 == 32'd1))) begin
            ap_phi_mux_out_pix_data_2_phi_fu_170_p6 = sext_ln61_fu_340_p1;
        end else if ((mode_read_reg_374 == 32'd1)) begin
            ap_phi_mux_out_pix_data_2_phi_fu_170_p6 = rgb_out_fu_280_p4;
        end else begin
            ap_phi_mux_out_pix_data_2_phi_fu_170_p6 = ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167;
        end
    end else begin
        ap_phi_mux_out_pix_data_2_phi_fu_170_p6 = ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_345_ce = 1'b1;
    end else begin
        grp_fu_345_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_353_ce = 1'b1;
    end else begin
        grp_fu_353_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln32_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TDATA_blk_n = s_axis_video_TVALID;
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TREADY = 1'b1;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_192_p2 = (indvar_flatten_fu_102 + 64'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axis_video_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axis_video_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln32_fu_187_p2 == 1'd0) & (s_axis_video_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (m_axis_video_TREADY == 1'b0);
end

always @ (*) begin
    ap_condition_216 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167 = 'bx;

assign b_fu_246_p1 = s_axis_video_TDATA[7:0];

assign gray_fu_271_p4 = {{grp_fu_353_p3[15:8]}};

assign grp_fu_345_p0 = grp_fu_345_p00;

assign grp_fu_345_p00 = r_fu_226_p4;

assign grp_fu_345_p1 = 15'd77;

assign grp_fu_353_p0 = grp_fu_353_p00;

assign grp_fu_353_p00 = b_reg_427;

assign grp_fu_353_p1 = 13'd29;

assign icmp_ln32_fu_187_p2 = ((indvar_flatten_fu_102 == mul_ln9) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_295_p2 = (($signed(zext_ln59_fu_291_p1) < $signed(threshold)) ? 1'b1 : 1'b0);

assign m_axis_video_TDATA = ap_phi_mux_out_pix_data_2_phi_fu_170_p6;

assign m_axis_video_TDEST = out_pix_dest_reg_417_pp0_iter4_reg;

assign m_axis_video_TID = out_pix_id_reg_412_pp0_iter4_reg;

assign m_axis_video_TKEEP = out_pix_keep_reg_392_pp0_iter4_reg;

assign m_axis_video_TLAST = out_pix_last_reg_407_pp0_iter4_reg;

assign m_axis_video_TSTRB = out_pix_strb_reg_397_pp0_iter4_reg;

assign m_axis_video_TUSER = out_pix_user_reg_402_pp0_iter4_reg;

assign mode_read_reg_374 = mode;

assign mul_ln6_1_fu_265_p0 = mul_ln6_1_fu_265_p00;

assign mul_ln6_1_fu_265_p00 = g_reg_422_pp0_iter2_reg;

assign mul_ln6_1_fu_265_p1 = 16'd150;

assign outv_fu_300_p2 = (icmp_ln59_fu_295_p2 ^ 1'd1);

assign r_fu_226_p4 = {{s_axis_video_TDATA[23:16]}};

assign rgb_out_2_fu_330_p4 = {{{select_ln60_fu_314_p3}, {select_ln60_1_fu_322_p3}}, {select_ln59_fu_306_p3}};

assign rgb_out_fu_280_p4 = {{{gray_fu_271_p4}, {gray_fu_271_p4}}, {gray_fu_271_p4}};

assign select_ln59_fu_306_p3 = ((outv_fu_300_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln60_1_fu_322_p3 = ((outv_fu_300_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln60_fu_314_p3 = ((outv_fu_300_p2[0:0] == 1'b1) ? 1'd1 : 1'd0);

assign sext_ln61_fu_340_p1 = $signed(rgb_out_2_fu_330_p4);

assign zext_ln59_fu_291_p1 = gray_fu_271_p4;

endmodule //gbt24_gbt24_Pipeline_Row_Loop_Col_Loop
