domain_path: C:\selected_topics_hdmi\pyzq\baremetal\vitis_workspace\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx_vitis\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
