# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/hw_constr.xdc

# Block Designs: bd/video_out_pynq_z2/video_out_pynq_z2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2 || ORIG_REF_NAME==video_out_pynq_z2} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_0_0/video_out_pynq_z2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axi_gpio_0_0 || ORIG_REF_NAME==video_out_pynq_z2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_clk_wiz_0_0/video_out_pynq_z2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_clk_wiz_0_0 || ORIG_REF_NAME==video_out_pynq_z2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_constant_high_0/video_out_pynq_z2_constant_high_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_constant_high_0 || ORIG_REF_NAME==video_out_pynq_z2_constant_high_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_constant_low_0/video_out_pynq_z2_constant_low_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_constant_low_0 || ORIG_REF_NAME==video_out_pynq_z2_constant_low_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_proc_sys_vid_clk_0/video_out_pynq_z2_proc_sys_vid_clk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_proc_sys_vid_clk_0 || ORIG_REF_NAME==video_out_pynq_z2_proc_sys_vid_clk_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_processing_system7_0_0/video_out_pynq_z2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_processing_system7_0_0 || ORIG_REF_NAME==video_out_pynq_z2_processing_system7_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_rgb2dvi_0_0/video_out_pynq_z2_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_rgb2dvi_0_0 || ORIG_REF_NAME==video_out_pynq_z2_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_rst_ps7_0_100M_0/video_out_pynq_z2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_rst_ps7_0_100M_0 || ORIG_REF_NAME==video_out_pynq_z2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/video_out_pynq_z2_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_smartconnect_0_0 || ORIG_REF_NAME==video_out_pynq_z2_smartconnect_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_axi4s_vid_out_0_0/video_out_pynq_z2_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==video_out_pynq_z2_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tc_0_0/video_out_pynq_z2_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_v_tc_0_0 || ORIG_REF_NAME==video_out_pynq_z2_v_tc_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/video_out_pynq_z2_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_dvi2rgb_0_0 || ORIG_REF_NAME==video_out_pynq_z2_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_vid_in_axi4s_0_0/video_out_pynq_z2_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==video_out_pynq_z2_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_1_0/video_out_pynq_z2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axi_gpio_1_0 || ORIG_REF_NAME==video_out_pynq_z2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_2_0/video_out_pynq_z2_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axi_gpio_2_0 || ORIG_REF_NAME==video_out_pynq_z2_axi_gpio_2_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_util_vector_logic_0_0/video_out_pynq_z2_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_util_vector_logic_0_0 || ORIG_REF_NAME==video_out_pynq_z2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_video_gray_live_0_0/video_out_pynq_z2_video_gray_live_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_video_gray_live_0_0 || ORIG_REF_NAME==video_out_pynq_z2_video_gray_live_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axis_data_fifo_0_0/video_out_pynq_z2_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axis_data_fifo_0_0 || ORIG_REF_NAME==video_out_pynq_z2_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axis_register_slice_0_0/video_out_pynq_z2_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axis_register_slice_0_0 || ORIG_REF_NAME==video_out_pynq_z2_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_3_0/video_out_pynq_z2_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_pynq_z2_axi_gpio_3_0 || ORIG_REF_NAME==video_out_pynq_z2_axi_gpio_3_0} -quiet] -quiet

# XDC: c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/video_out_pynq_z2_ooc.xdc
