# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.runs/synth_1/video_out_pynq_z2_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.cache/wt [current_project]
set_property parent.project_path C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/selected_topics_hdmi/pyzq/vivado-library
  c:/selected_topics_hdmi/pyzq/hw/ip_repo
  c:/selected_topics_hdmi/pyzq/hw/hls_gray_ip/hls_export/myip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/hdl/video_out_pynq_z2_wrapper.v
add_files C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.srcs/sources_1/bd/video_out_pynq_z2/video_out_pynq_z2.bd
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_0_0/video_out_pynq_z2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_0_0/video_out_pynq_z2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_0_0/video_out_pynq_z2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_clk_wiz_0_0/video_out_pynq_z2_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_clk_wiz_0_0/video_out_pynq_z2_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_clk_wiz_0_0/video_out_pynq_z2_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_proc_sys_vid_clk_0/video_out_pynq_z2_proc_sys_vid_clk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_proc_sys_vid_clk_0/video_out_pynq_z2_proc_sys_vid_clk_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_proc_sys_vid_clk_0/video_out_pynq_z2_proc_sys_vid_clk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_processing_system7_0_0/video_out_pynq_z2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rst_ps7_0_100M_0/video_out_pynq_z2_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rst_ps7_0_100M_0/video_out_pynq_z2_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_rst_ps7_0_100M_0/video_out_pynq_z2_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_1/bd_98e7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_1/bd_98e7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_2/bd_98e7_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_3/bd_98e7_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_4/bd_98e7_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_5/bd_98e7_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_6/bd_98e7_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_7/bd_98e7_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_8/bd_98e7_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_9/bd_98e7_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_10/bd_98e7_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_11/bd_98e7_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_12/bd_98e7_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_12/bd_98e7_arni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_13/bd_98e7_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_13/bd_98e7_rni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_14/bd_98e7_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_14/bd_98e7_awni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_15/bd_98e7_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_15/bd_98e7_wni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_16/bd_98e7_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_16/bd_98e7_bni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_20/bd_98e7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_21/bd_98e7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_21/bd_98e7_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_22/bd_98e7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_22/bd_98e7_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_23/bd_98e7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_23/bd_98e7_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_24/bd_98e7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_24/bd_98e7_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_25/bd_98e7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_25/bd_98e7_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_26/bd_98e7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_27/bd_98e7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_27/bd_98e7_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_28/bd_98e7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_28/bd_98e7_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_29/bd_98e7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_29/bd_98e7_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_30/bd_98e7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_30/bd_98e7_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_31/bd_98e7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_31/bd_98e7_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_33/bd_98e7_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_34/bd_98e7_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_34/bd_98e7_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_35/bd_98e7_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_35/bd_98e7_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_36/bd_98e7_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_36/bd_98e7_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_37/bd_98e7_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_37/bd_98e7_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_38/bd_98e7_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_38/bd_98e7_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_40/bd_98e7_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_41/bd_98e7_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_41/bd_98e7_m02arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_42/bd_98e7_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_42/bd_98e7_m02rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_43/bd_98e7_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_43/bd_98e7_m02awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_44/bd_98e7_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_44/bd_98e7_m02wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_45/bd_98e7_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_45/bd_98e7_m02bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_47/bd_98e7_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_48/bd_98e7_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_48/bd_98e7_m03arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_49/bd_98e7_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_49/bd_98e7_m03rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_50/bd_98e7_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_50/bd_98e7_m03awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_51/bd_98e7_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_51/bd_98e7_m03wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_52/bd_98e7_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_52/bd_98e7_m03bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_54/bd_98e7_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_55/bd_98e7_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_55/bd_98e7_m04arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_56/bd_98e7_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_56/bd_98e7_m04rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_57/bd_98e7_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_57/bd_98e7_m04awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_58/bd_98e7_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_58/bd_98e7_m04wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_59/bd_98e7_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_59/bd_98e7_m04bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_61/bd_98e7_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_62/bd_98e7_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_62/bd_98e7_m05arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_63/bd_98e7_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_63/bd_98e7_m05rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_64/bd_98e7_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_64/bd_98e7_m05awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_65/bd_98e7_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_65/bd_98e7_m05wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_66/bd_98e7_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/bd_0/ip/ip_66/bd_98e7_m05bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_axi4s_vid_out_0_0/video_out_pynq_z2_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_axi4s_vid_out_0_0/video_out_pynq_z2_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tc_0_0/video_out_pynq_z2_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tc_0_0/video_out_pynq_z2_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/ila_pixclk/ila_pixclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/ila_timing_workaround.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_dvi2rgb_0_0/src/ila_refclk/ila_refclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_vid_in_axi4s_0_0/video_out_pynq_z2_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_vid_in_axi4s_0_0/video_out_pynq_z2_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_1_0/video_out_pynq_z2_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_1_0/video_out_pynq_z2_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_1_0/video_out_pynq_z2_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_2_0/video_out_pynq_z2_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_2_0/video_out_pynq_z2_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_2_0/video_out_pynq_z2_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_video_gray_live_0_0/constraints/video_gray_live_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axis_data_fifo_0_0/video_out_pynq_z2_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axis_register_slice_0_0/video_out_pynq_z2_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axis_register_slice_0_0/video_out_pynq_z2_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_3_0/video_out_pynq_z2_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_3_0/video_out_pynq_z2_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_axi_gpio_3_0/video_out_pynq_z2_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/video_out_pynq_z2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.srcs/constrs_1/imports/constr/hw_constr.xdc
set_property used_in_implementation false [get_files C:/selected_topics_hdmi/pyzq/hw/hw_proj/hw_proj.srcs/constrs_1/imports/constr/hw_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top video_out_pynq_z2_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef video_out_pynq_z2_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file video_out_pynq_z2_wrapper_utilization_synth.rpt -pb video_out_pynq_z2_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
