-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gbt24_gbt24_Pipeline_Row_Loop_Col_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TVALID : IN STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    mul_ln9 : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    mode : IN STD_LOGIC_VECTOR (31 downto 0);
    threshold : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of gbt24_gbt24_Pipeline_Row_Loop_Col_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_4D : STD_LOGIC_VECTOR (14 downto 0) := "000000001001101";
    constant ap_const_lv13_1D : STD_LOGIC_VECTOR (12 downto 0) := "0000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln32_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal m_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal s_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal mode_read_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln32_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_383_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_383_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_383_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_keep_reg_392 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_keep_reg_392_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_keep_reg_392_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_keep_reg_392_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_strb_reg_397 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_strb_reg_397_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_strb_reg_397_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_strb_reg_397_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal out_pix_user_reg_402 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_user_reg_402_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_user_reg_402_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_user_reg_402_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_last_reg_407 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_last_reg_407_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_last_reg_407_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_last_reg_407_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_id_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_id_reg_412_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_id_reg_412_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_id_reg_412_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_dest_reg_417 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_dest_reg_417_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_dest_reg_417_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_dest_reg_417_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal g_reg_422 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_reg_422_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_246_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_427 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln6_1_fu_265_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_out_pix_data_2_phi_fu_170_p6 : STD_LOGIC_VECTOR (23 downto 0);
    signal rgb_out_fu_280_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln61_fu_340_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_pred205_state6 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167 : STD_LOGIC_VECTOR (23 downto 0);
    signal indvar_flatten_fu_102 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln32_fu_192_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal r_fu_226_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln6_1_fu_265_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln6_1_fu_265_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_353_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal gray_fu_271_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln59_fu_291_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln59_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outv_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_1_fu_322_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln59_fu_306_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rgb_out_2_fu_330_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_345_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_345_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_353_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_353_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_345_ce : STD_LOGIC;
    signal grp_fu_353_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_345_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_353_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln6_1_fu_265_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_216 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component gbt24_mul_8ns_9ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component gbt24_mac_muladd_8ns_7ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component gbt24_mac_muladd_8ns_5ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component gbt24_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_9ns_16_1_1_U1 : component gbt24_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln6_1_fu_265_p0,
        din1 => mul_ln6_1_fu_265_p1,
        dout => mul_ln6_1_fu_265_p2);

    mac_muladd_8ns_7ns_16ns_16_4_1_U2 : component gbt24_mac_muladd_8ns_7ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_345_p0,
        din1 => grp_fu_345_p1,
        din2 => mul_ln6_1_fu_265_p2,
        ce => grp_fu_345_ce,
        dout => grp_fu_345_p3);

    mac_muladd_8ns_5ns_16ns_16_4_1_U3 : component gbt24_mac_muladd_8ns_5ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_353_p0,
        din1 => grp_fu_353_p1,
        din2 => grp_fu_345_p3,
        ce => grp_fu_353_ce,
        dout => grp_fu_353_p3);

    flow_control_loop_pipe_sequential_init_U : component gbt24_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_216)) then
                if (((icmp_ln32_fu_187_p2 = ap_const_lv1_0) and (mode_read_reg_374 = ap_const_lv32_0))) then 
                    ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167 <= s_axis_video_TDATA;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_102 <= ap_const_lv64_0;
                elsif (((icmp_ln32_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_102 <= add_ln32_fu_192_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                b_reg_427 <= b_fu_246_p1;
                g_reg_422 <= s_axis_video_TDATA(15 downto 8);
                icmp_ln32_reg_383 <= icmp_ln32_fu_187_p2;
                out_pix_dest_reg_417 <= s_axis_video_TDEST;
                out_pix_id_reg_412 <= s_axis_video_TID;
                out_pix_keep_reg_392 <= s_axis_video_TKEEP;
                out_pix_last_reg_407 <= s_axis_video_TLAST;
                out_pix_strb_reg_397 <= s_axis_video_TSTRB;
                out_pix_user_reg_402 <= s_axis_video_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                    ap_predicate_pred205_state6 <= (not((mode_read_reg_374 = ap_const_lv32_0)) and not((mode_read_reg_374 = ap_const_lv32_1)) and (icmp_ln32_reg_383_pp0_iter3_reg = ap_const_lv1_0));
                g_reg_422_pp0_iter2_reg <= g_reg_422;
                icmp_ln32_reg_383_pp0_iter2_reg <= icmp_ln32_reg_383;
                icmp_ln32_reg_383_pp0_iter3_reg <= icmp_ln32_reg_383_pp0_iter2_reg;
                icmp_ln32_reg_383_pp0_iter4_reg <= icmp_ln32_reg_383_pp0_iter3_reg;
                out_pix_dest_reg_417_pp0_iter2_reg <= out_pix_dest_reg_417;
                out_pix_dest_reg_417_pp0_iter3_reg <= out_pix_dest_reg_417_pp0_iter2_reg;
                out_pix_dest_reg_417_pp0_iter4_reg <= out_pix_dest_reg_417_pp0_iter3_reg;
                out_pix_id_reg_412_pp0_iter2_reg <= out_pix_id_reg_412;
                out_pix_id_reg_412_pp0_iter3_reg <= out_pix_id_reg_412_pp0_iter2_reg;
                out_pix_id_reg_412_pp0_iter4_reg <= out_pix_id_reg_412_pp0_iter3_reg;
                out_pix_keep_reg_392_pp0_iter2_reg <= out_pix_keep_reg_392;
                out_pix_keep_reg_392_pp0_iter3_reg <= out_pix_keep_reg_392_pp0_iter2_reg;
                out_pix_keep_reg_392_pp0_iter4_reg <= out_pix_keep_reg_392_pp0_iter3_reg;
                out_pix_last_reg_407_pp0_iter2_reg <= out_pix_last_reg_407;
                out_pix_last_reg_407_pp0_iter3_reg <= out_pix_last_reg_407_pp0_iter2_reg;
                out_pix_last_reg_407_pp0_iter4_reg <= out_pix_last_reg_407_pp0_iter3_reg;
                out_pix_strb_reg_397_pp0_iter2_reg <= out_pix_strb_reg_397;
                out_pix_strb_reg_397_pp0_iter3_reg <= out_pix_strb_reg_397_pp0_iter2_reg;
                out_pix_strb_reg_397_pp0_iter4_reg <= out_pix_strb_reg_397_pp0_iter3_reg;
                out_pix_user_reg_402_pp0_iter2_reg <= out_pix_user_reg_402;
                out_pix_user_reg_402_pp0_iter3_reg <= out_pix_user_reg_402_pp0_iter2_reg;
                out_pix_user_reg_402_pp0_iter4_reg <= out_pix_user_reg_402_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter2_out_pix_data_2_reg_167;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter3_out_pix_data_2_reg_167;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167 <= ap_phi_reg_pp0_iter4_out_pix_data_2_reg_167;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln32_fu_192_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_102) + unsigned(ap_const_lv64_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter1, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter1, m_axis_video_TREADY, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((m_axis_video_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state2_pp0_stage0_iter1, m_axis_video_TREADY, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((m_axis_video_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(s_axis_video_TVALID, icmp_ln32_fu_187_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln32_fu_187_p2 = ap_const_lv1_0) and (s_axis_video_TVALID = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(m_axis_video_TREADY)
    begin
                ap_block_state6_pp0_stage0_iter5 <= (m_axis_video_TREADY = ap_const_logic_0);
    end process;


    ap_condition_216_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_216 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln32_fu_187_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln32_fu_187_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_out_pix_data_2_phi_fu_170_p6_assign_proc : process(mode_read_reg_374, icmp_ln32_reg_383_pp0_iter4_reg, rgb_out_fu_280_p4, ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167, sext_ln61_fu_340_p1)
    begin
        if ((icmp_ln32_reg_383_pp0_iter4_reg = ap_const_lv1_0)) then
            if ((not((mode_read_reg_374 = ap_const_lv32_0)) and not((mode_read_reg_374 = ap_const_lv32_1)))) then 
                ap_phi_mux_out_pix_data_2_phi_fu_170_p6 <= sext_ln61_fu_340_p1;
            elsif ((mode_read_reg_374 = ap_const_lv32_1)) then 
                ap_phi_mux_out_pix_data_2_phi_fu_170_p6 <= rgb_out_fu_280_p4;
            else 
                ap_phi_mux_out_pix_data_2_phi_fu_170_p6 <= ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167;
            end if;
        else 
            ap_phi_mux_out_pix_data_2_phi_fu_170_p6 <= ap_phi_reg_pp0_iter5_out_pix_data_2_reg_167;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_out_pix_data_2_reg_167 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    b_fu_246_p1 <= s_axis_video_TDATA(8 - 1 downto 0);
    gray_fu_271_p4 <= grp_fu_353_p3(15 downto 8);

    grp_fu_345_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_345_ce <= ap_const_logic_1;
        else 
            grp_fu_345_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_345_p0 <= grp_fu_345_p00(8 - 1 downto 0);
    grp_fu_345_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_226_p4),15));
    grp_fu_345_p1 <= ap_const_lv15_4D(7 - 1 downto 0);

    grp_fu_353_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_353_ce <= ap_const_logic_1;
        else 
            grp_fu_353_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_353_p0 <= grp_fu_353_p00(8 - 1 downto 0);
    grp_fu_353_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_427),13));
    grp_fu_353_p1 <= ap_const_lv13_1D(5 - 1 downto 0);
    icmp_ln32_fu_187_p2 <= "1" when (indvar_flatten_fu_102 = mul_ln9) else "0";
    icmp_ln59_fu_295_p2 <= "1" when (signed(zext_ln59_fu_291_p1) < signed(threshold)) else "0";
    m_axis_video_TDATA <= ap_phi_mux_out_pix_data_2_phi_fu_170_p6;

    m_axis_video_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, m_axis_video_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            m_axis_video_TDATA_blk_n <= m_axis_video_TREADY;
        else 
            m_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_video_TDEST <= out_pix_dest_reg_417_pp0_iter4_reg;
    m_axis_video_TID <= out_pix_id_reg_412_pp0_iter4_reg;
    m_axis_video_TKEEP <= out_pix_keep_reg_392_pp0_iter4_reg;
    m_axis_video_TLAST <= out_pix_last_reg_407_pp0_iter4_reg;
    m_axis_video_TSTRB <= out_pix_strb_reg_397_pp0_iter4_reg;
    m_axis_video_TUSER <= out_pix_user_reg_402_pp0_iter4_reg;

    m_axis_video_TVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            m_axis_video_TVALID <= ap_const_logic_1;
        else 
            m_axis_video_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    mode_read_reg_374 <= mode;
    mul_ln6_1_fu_265_p0 <= mul_ln6_1_fu_265_p00(8 - 1 downto 0);
    mul_ln6_1_fu_265_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_reg_422_pp0_iter2_reg),16));
    mul_ln6_1_fu_265_p1 <= ap_const_lv16_96(9 - 1 downto 0);
    outv_fu_300_p2 <= (icmp_ln59_fu_295_p2 xor ap_const_lv1_1);
    r_fu_226_p4 <= s_axis_video_TDATA(23 downto 16);
    rgb_out_2_fu_330_p4 <= ((select_ln60_fu_314_p3 & select_ln60_1_fu_322_p3) & select_ln59_fu_306_p3);
    rgb_out_fu_280_p4 <= ((gray_fu_271_p4 & gray_fu_271_p4) & gray_fu_271_p4);

    s_axis_video_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, s_axis_video_TVALID, icmp_ln32_fu_187_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln32_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_video_TDATA_blk_n <= s_axis_video_TVALID;
        else 
            s_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln32_fu_187_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln32_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_video_TREADY <= ap_const_logic_1;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln59_fu_306_p3 <= 
        ap_const_lv8_FF when (outv_fu_300_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln60_1_fu_322_p3 <= 
        ap_const_lv8_FF when (outv_fu_300_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln60_fu_314_p3 <= 
        ap_const_lv1_1 when (outv_fu_300_p2(0) = '1') else 
        ap_const_lv1_0;
        sext_ln61_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rgb_out_2_fu_330_p4),24));

    zext_ln59_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gray_fu_271_p4),32));
end behav;
